version: 2.1

description: Tasks for managing Node modules in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/node-orb/blob/master/config.yml"

commands:
  cache-read:
    steps:
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
  cache-write:
    steps:
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ./node_modules

  install:
    steps:
      - run: "yarn install --cache-folder=~/.cache/yarn --frozen-lockfile"
