version: 2.1

description: Tasks for managing NPM Node modules in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/node-orb/blob/main/config.yml"

commands:
  cache-read:
    steps:
      - restore_cache:
          keys:
            - npm-cache-{{ arch }}-{{ .Branch }}-{{checksum "package-lock.json" }}
  cache-write:
    steps:
      - save_cache:
          key: npm-cache-{{ arch }}-{{ .Branch }}-{{checksum "package-lock.json" }}
          paths:
            - ~/.cache
            - ./node_modules
  install:
    steps:
      - run:
          name: Install node dependencies
          command: "npm i"
