version: 2.1

description: Tasks for managing NPM Node modules in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/node-orb/blob/main/config.yml"

commands:
  cache-read:
    steps:
      - restore_cache:
          keys:
            - node-cache-{{ arch }}-{{checksum "package-lock.json" }}
          name: Restore Node modules cache
  cache-write:
    steps:
      - save_cache:
          key: node-cache-{{ arch }}-{{checksum "package-lock.json" }}
          name: Save Node modules cache
          paths:
            - ~/.cache
            - ./node_modules
  install:
    steps:
      - run:
          name: Install Node modules
          command: "npm i"
